import { CounterfeitComponent } from "./counterfeit/counterfeit.component";
import { NcrbComponent } from "./ncrb/ncrb.component";

export const PATH = {
  
  TOP20_SUBMIT_APPROVE_REJECT:"accounts/action",
  TOP20_GET_ROLES: "accounts/roleForReport/",
  TOP20_PATCH: "accounts",
  TOP20_REPORT_NAMES: "accounts/reports",
  TOP20_GET: "accounts",
  TOP20_FILE_IMPORT: "accounts/import",
  POSITION_GET_ALL: "annexures/annexures",
  POSITION_GET_RECORDS: "annexures",
  POSITION_GET_ROLES : "annexures/roleForAnnexure/",
  POSITION_POST_SUBMIT_APPROVE_REJECT:"annexures/action",
  POSITION_PATCH_UPDATE: "annexures",
  POSITION_POST_SAVE_CREATE: "annexures",
  ANNEX: "advances",
  ANNEX_POST: "advances/submit",
  COMPLIANCE_CATALOG: "complianceCatalog",
  COMPLIANCE_REVIEW: "complianceReview",
  COMPLIANCE_REPORT_NAMES: "complianceReview/getRecordsPerCategory",
  ACCOUNT_BORROWALS_STD: "accountBorrowals/standard",
  ACCOUNT_BORROWALS_STD_UPDATE: "accountBorrowals/standard/updateAll",
  ACCOUNT_BORROWALS_STD_SUBMIT: "accountBorrowals/standard/submitAll",
  ACCOUNT_BORROWALS_STD_IMPORT: "accountBorrowals/standard/import",
  ACCOUNT_BORROWALS_NPA: "accountBorrowals/npa",
  ACCOUNT_BORROWALS_NPA_UPDATE: "accountBorrowals/npa/updateAll",
  ACCOUNT_BORROWALS_NPA_SUBMIT: "accountBorrowals/npa/submitAll",
  ACCOUNT_BORROWALS_NPA_IMPORT: "accountBorrowals/npa/import",
  ACCOUNT_STRESSED: "accountsStressed",
  ACCOUNT_STRESSED_UPDATE: "accountsStressed/updateAll",
  ACCOUNT_STRESSED_SUBMIT: "accountsStressed/submitAll",
  ACCOUNT_STRESSED_IMPORT: "accountsStressed/import",
  ACCOUNT_WATCHlIST: "accountsWatchlist",
  ACCOUNT_WATCHlIST_UPDATE: "accountsWatchlist/updateAll",
  ACCOUNT_WATCHlIST_SUBMIT: "accountsWatchlist/submitAll",
  ACCOUNT_WATCHlIST_IMPORT: "accountsWatchlist/import",
  ACCOUNT_REGULATORY_NPA: "accountsSpecialRegulatory/npa",
  ACCOUNT_REGULATORY_NPA_UPDATE: "accountsSpecialRegulatory/npa/updateAll",
  ACCOUNT_REGULATORY_NPA_SUBMIT: "accountsSpecialRegulatory/npa/submitAll",
  ACCOUNT_REGULATORY_NPA_IMPORT: "accountsSpecialRegulatory/npa/import",
  ACCOUNT_REGULATORY_STD: "accountsSpecialRegulatory/standard",
  ACCOUNT_REGULATORY_STD_UPDATE: "accountsSpecialRegulatory/standard/updateAll",
  ACCOUNT_REGULATORY_STD_SUBMIT: "accountsSpecialRegulatory/standard/submitAll",
  ACCOUNT_REGULATORY_STD_IMPORT: "accountsSpecialRegulatory/standard/import",
  ACCOUNT_DCCO_DEFERMENT: "accountDCCODeferment",
  ACCOUNT_DCCO_DEFERMENT_UPDATE: "accountDCCODeferment/updateAll",
  ACCOUNT_DCCO_DEFERMENT_SUBMIT: "accountDCCODeferment/submitAll",
  ACCOUNT_DCCO_DEFERMENT_IMPORT: "accountDCCODeferment/import",
  ACCOUNT_RP_IMPLEMENTED_NPA: "accountRPImplemented/npa",
  ACCOUNT_RP_IMPLEMENTED_NPA_UPDATE: "accountRPImplemented/npa/updateAll",
  ACCOUNT_RP_IMPLEMENTED_NPA_SUBMIT: "accountRPImplemented/npa/submitAll",
  ACCOUNT_RP_IMPLEMENTED_NPA_IMPORT: "accountRPImplemented/npa/import",
  ACCOUNT_RP_IMPLEMENTED_STD: "accountRPImplemented/standard",
  ACCOUNT_RP_IMPLEMENTED_STD_UPDATE: "accountRPImplemented/standard/updateAll",
  ACCOUNT_RP_IMPLEMENTED_STD_SUBMIT: "accountRPImplemented/standard/submitAll",
  ACCOUNT_RP_IMPLEMENTED_STD_IMPORT: "accountRPImplemented/standard/import",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA: "accountRPNotImplemented/npa",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_UPDATE:
    "accountRPNotImplemented/npa/updateAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_SUBMIT:
    "accountRPNotImplemented/npa/submitAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_IMPORT: "accountRPNotImplemented/npa/import",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD: "accountRPNotImplemented/standard",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_UPDATE:
    "accountRPNotImplemented/standard/updateAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_SUBMIT:
    "accountRPNotImplemented/standard/submitAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_IMPORT:
    "accountRPNotImplemented/standard/import",
  ACCOUNT_IBC_STD: "accountIBC/standard",
  ACCOUNT_IBC_STD_UPDATE: "accountIBC/standard/updateAll",
  ACCOUNT_IBC_STD_SUBMIT: "accountIBC/standard/submitAll",
  ACCOUNT_IBC_STD_IMPORT: "accountIBC/standard/import",
  ACCOUNT_IBC_NPA: "accountIBC/npa",
  ACCOUNT_IBC_NPA_UPDATE: "accountIBC/npa/updateAll",
  ACCOUNT_IBC_NPA_SUBMIT: "accountIBC/npa/submitAll",
  ACCOUNT_IBC_NPA_IMPORT: "accountIBC/npa/import",
  RECOVERY_INITIATIVE: "recoveryInitiatives",
  RECOVERY_INITIATIVE_SUBMIT: "recoveryInitiatives/submit",
  PIPELINE_STRESS: "pipelineStress",
  PIPELINE_STRESS_SUBMIT: "pipelineStress/submit",
  EXTERNAL_RATING: "externalRating",
  EXTERNAL_RATING_SUBMIT: "externalRating/submit",
  EXTERNAL_RATING_APPROVE_REJECT: "externalRating/checker/",
  PERFORMANCE_INDICATOR: "performanceIndicator",
  PERFORMANCE_INDICATOR_SUBMIT: "performanceIndicator/submitAll",
  AREA_WISE: "areaWiseBreakup",
  AREA_WISE_SUBMIT: "areaWiseBreakup/submitAll",
  AP_WISE: "apWiseBreakup",
  AP_WISE_SUBMIT: "apWiseBreakup/submitAll",
  METRICS: "metrics",
  METRICS_SUBMIT: "metrics/submitAll",
  OMBUDSMAN_GETBRANCHNAME: "ombudsman/getBranchName/",
  EQUIFAX_GETBRANCHNAME: "equifaxCredit/getBranchName/",
  EQUIFAX_GETCUSTOMERNAME: "equifaxCredit/getCustomerName/",
  OMBUDSMAN_GETCUSTOMERNAME: "ombudsman/getCustomerName/",
  OMBUDSMAN_CREATE: "ombudsman",
  OMBUDSMAN_SUBMITALL: "ombudsman/submitAll",
  OMBUDSMAN_SUBMITTED_BY_CUSTOMER: "ombudsman/getSubmittedRecords/",
  COUNTERFEIT_GET_ALL : "counterfeit",
  COUNTERFEIT_SUBMIT : "counterfeit",
  COUNTERFEIT_EDIT : "counterfeit",
  NCRB_GET : "ncrb"  ,
  NCRB_SUBMIT : "ncrb" ,
  NCRB_EDIT : "ncrb" , 
  FORTNIGHTLY_SUBMIT : "fortnightly",
  GET_FORTNIGHTLY_DATA : "fortnightly",
  UNRECONCILED_SUBMIT : "UnreconciledEntries",
  GET_UNRECONCILED_DATA : "UnreconciledEntries",
  GET_UNRECONCILED_DATA_BY_STATUS : "UnreconciledEntries/byStatus",
  NOSTRO_SUBMIT : "NostroAccounts",
  GET_NOSTRO_DATA : "NostroAccounts",
  GET_NOSTRO_DATA_BY_STATUS : "NostroAccounts/byStatus",
  EQUIFAX_SUBMIT : "equifaxCredit",
  GET_EQUIFAX_DATA : "equifaxCredit",
  EXPOSURE_QCCP_SUBMIT : "ExposureQCCP",
  EXPOSURE_QCCP_GET_RECORDS : "ExposureQCCP",
  TIER1CAPITAL:'ExposureQCCP/tier1Capital',
  OMBUDSMAN_GETBRANCHCODES: "ombudsman/getSerialNumber",
  GET_USER: "userDetails/",
  GET_ALL_USER: "userDetails/allUsers/",
  GET_ALL_SSOUSER: "userDetails/allSSOUsers",
  GET_USER_ROLES: "userDetails/rolesByUsername/",
  AVAILABLE_ROLES: "userDetails/availableRoles/",
  ASSIGNEE_USERS : "userDetails/allSSOUsers",
  COMPLIENCE_USERS : "userDetails/allComplianceUsers",
  USER: "userDetails",
  COMPLIANCE_USERS : "userDetails/allComplianceUsers" , 
  USER_ROLES: "userDetails/rolesByUsername/",
  COMPLIANCE_GET_ALL : "complianceReports",
  COMPLIANCE_GET_SINGLE_RECORD : "complianceReports/getSingleRecord",
  COMPLIANCE_POST_SUBMIT : "complianceReports/",
  COMPLIANCE_SEARCH : "complianceReports/searchByValue",
  DOWNLOAD_EXCEL: "complianceReview/recordsPerCategory/export/excel",
  PATCH_EDIT: "ombudsman/edit",
  INFORMATIONREPORT_SUBMIT:"InformationReport",
  INFORMATIONREPORT_GET:"InformationReport",
  INFORMATIONREPORT_GETBYID:"InformationReport/byId",
  INFORMATIONREPORT_PUT:"InformationReport",
  INFORMATIONREPORT_STATUS:"InformationReport/byStatus",
  OWNERSHIPREPORTS_SUBMIT:"ownershipReports",
};


export const SERVER_PATHS = {

  DEV_HTTP: "http://172.16.15.223:8080/gap-api/api/v1/",
  DEV_HTTPS: "https://172.16.15.223:8443/gap-api/api/v1/",

  PROD_HTTP: "http://ssoedwdcap.edw.obc.co.in:8080/gap-api/api/v1/",
  PROD_HTTPS: "https://ssoedwdcap.edw.obc.co.in:8443/gap-api/api/v1/",


  DEV: "http://172.16.15.223:8080/gap-api/api/v1/",
   LOCAL_HTTP: "http://3.95.36.75:8014/api/v1/",
   
  // LOCAL_HTTP: "http://localhosts:8014/api/v1/",

};
