import { Alert } from "selenium-webdriver";
import { CounterfeitComponent } from "./counterfeit/counterfeit.component";
import { NcrbComponent } from "./ncrb/ncrb.component";

export const PATH = {
  
  TOP20_SUBMIT_APPROVE_REJECT:"accounts/action",
  TOP20_GET_ROLES: "accounts/roleForReport/",
  TOP20_PATCH: "accounts",
  TOP20_REPORT_NAMES: "accounts/reports",
  TOP20_GET: "accounts",
  TOP20_FILE_IMPORT: "accounts/import",
  POSITION_GET_ALL: "annexures/annexures",
  POSITION_GET_RECORDS: "annexures",
  POSITION_GET_ROLES : "annexures/roleForAnnexure/",
  POSITION_POST_SUBMIT_APPROVE_REJECT:"annexures/action",
  POSITION_PATCH_UPDATE: "annexures",
  POSITION_POST_SAVE_CREATE: "annexures",
  ANNEX: "advances",
  ANNEX_POST: "advances/submit",
  COMPLIANCE_CATALOG: "complianceCatalog",
  COMPLIANCE_REVIEW: "complianceReview",
  COMPLIANCE_REPORT_NAMES: "complianceReview/getRecordsPerCategory",
  ACCOUNT_BORROWALS_STD: "accountBorrowals/standard",
  ACCOUNT_BORROWALS_STD_UPDATE: "accountBorrowals/standard/updateAll",
  ACCOUNT_BORROWALS_STD_SUBMIT: "accountBorrowals/standard/submitAll",
  ACCOUNT_BORROWALS_STD_IMPORT: "accountBorrowals/standard/import",
  ACCOUNT_BORROWALS_NPA: "accountBorrowals/npa",
  ACCOUNT_BORROWALS_NPA_UPDATE: "accountBorrowals/npa/updateAll",
  ACCOUNT_BORROWALS_NPA_SUBMIT: "accountBorrowals/npa/submitAll",
  ACCOUNT_BORROWALS_NPA_IMPORT: "accountBorrowals/npa/import",
  ACCOUNT_STRESSED: "accountsStressed",
  ACCOUNT_STRESSED_UPDATE: "accountsStressed/updateAll",
  ACCOUNT_STRESSED_SUBMIT: "accountsStressed/submitAll",
  ACCOUNT_STRESSED_IMPORT: "accountsStressed/import",
  ACCOUNT_WATCHlIST: "accountsWatchlist",
  ACCOUNT_WATCHlIST_UPDATE: "accountsWatchlist/updateAll",
  ACCOUNT_WATCHlIST_SUBMIT: "accountsWatchlist/submitAll",
  ACCOUNT_WATCHlIST_IMPORT: "accountsWatchlist/import",
  ACCOUNT_REGULATORY_NPA: "accountsSpecialRegulatory/npa",
  ACCOUNT_REGULATORY_NPA_UPDATE: "accountsSpecialRegulatory/npa/updateAll",
  ACCOUNT_REGULATORY_NPA_SUBMIT: "accountsSpecialRegulatory/npa/submitAll",
  ACCOUNT_REGULATORY_NPA_IMPORT: "accountsSpecialRegulatory/npa/import",
  ACCOUNT_REGULATORY_STD: "accountsSpecialRegulatory/standard",
  ACCOUNT_REGULATORY_STD_UPDATE: "accountsSpecialRegulatory/standard/updateAll",
  ACCOUNT_REGULATORY_STD_SUBMIT: "accountsSpecialRegulatory/standard/submitAll",
  ACCOUNT_REGULATORY_STD_IMPORT: "accountsSpecialRegulatory/standard/import",
  ACCOUNT_DCCO_DEFERMENT: "accountDCCODeferment",
  ACCOUNT_DCCO_DEFERMENT_UPDATE: "accountDCCODeferment/updateAll",
  ACCOUNT_DCCO_DEFERMENT_SUBMIT: "accountDCCODeferment/submitAll",
  ACCOUNT_DCCO_DEFERMENT_IMPORT: "accountDCCODeferment/import",
  ACCOUNT_RP_IMPLEMENTED_NPA: "accountRPImplemented/npa",
  ACCOUNT_RP_IMPLEMENTED_NPA_UPDATE: "accountRPImplemented/npa/updateAll",
  ACCOUNT_RP_IMPLEMENTED_NPA_SUBMIT: "accountRPImplemented/npa/submitAll",
  ACCOUNT_RP_IMPLEMENTED_NPA_IMPORT: "accountRPImplemented/npa/import",
  ACCOUNT_RP_IMPLEMENTED_STD: "accountRPImplemented/standard",
  ACCOUNT_RP_IMPLEMENTED_STD_UPDATE: "accountRPImplemented/standard/updateAll",
  ACCOUNT_RP_IMPLEMENTED_STD_SUBMIT: "accountRPImplemented/standard/submitAll",
  ACCOUNT_RP_IMPLEMENTED_STD_IMPORT: "accountRPImplemented/standard/import",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA: "accountRPNotImplemented/npa",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_UPDATE:"accountRPNotImplemented/npa/updateAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_SUBMIT:"accountRPNotImplemented/npa/submitAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_NPA_IMPORT: "accountRPNotImplemented/npa/import",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD: "accountRPNotImplemented/standard",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_UPDATE: "accountRPNotImplemented/standard/updateAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_SUBMIT:"accountRPNotImplemented/standard/submitAll",
  ACCOUNT_RP_NOT_IMPLEMENTED_STD_IMPORT:"accountRPNotImplemented/standard/import",
  ACCOUNT_IBC_STD: "accountIBC/standard",
  ACCOUNT_IBC_STD_UPDATE: "accountIBC/standard/updateAll",
  ACCOUNT_IBC_STD_SUBMIT: "accountIBC/standard/submitAll",
  ACCOUNT_IBC_STD_IMPORT: "accountIBC/standard/import",
  ACCOUNT_IBC_NPA: "accountIBC/npa",
  ACCOUNT_IBC_NPA_UPDATE: "accountIBC/npa/updateAll",
  ACCOUNT_IBC_NPA_SUBMIT: "accountIBC/npa/submitAll",
  ACCOUNT_IBC_NPA_IMPORT: "accountIBC/npa/import",
  RECOVERY_INITIATIVE: "recoveryInitiatives",
  RECOVERY_INITIATIVE_SUBMIT: "recoveryInitiatives/submit",
  PIPELINE_STRESS: "pipelineStress",
  PIPELINE_STRESS_SUBMIT: "pipelineStress/submit",
  EXTERNAL_RATING: "externalRating",
  EXTERNAL_RATING_SUBMIT: "externalRating/submit",
  EXTERNAL_RATING_APPROVE_REJECT: "externalRating/checker/",
  PERFORMANCE_INDICATOR: "performanceIndicator",
  PERFORMANCE_INDICATOR_SUBMIT: "performanceIndicator/submitAll",
  AREA_WISE: "areaWiseBreakup",
  AREA_WISE_SUBMIT: "areaWiseBreakup/submitAll",
  AP_WISE: "apWiseBreakup",
  AP_WISE_SUBMIT: "apWiseBreakup/submitAll",
  METRICS: "metrics",
  METRICS_SUBMIT: "metrics/submitAll",
  OMBUDSMAN_GETBRANCHNAME: "ombudsman/getBranchName/",
  EQUIFAX_GETBRANCHNAME: "equifaxCredit/getBranchName/",
  EQUIFAX_GETCUSTOMERNAME: "equifaxCredit/getCustomerName/",
  OMBUDSMAN_GETCUSTOMERNAME: "ombudsman/getCustomerName/",
  OMBUDSMAN_CREATE: "ombudsman",
  OMBUDSMAN_SUBMITALL: "ombudsman/submitAll",
  OMBUDSMAN_SUBMITTED_BY_CUSTOMER: "ombudsman/getSubmittedRecords/",
  OMBUDSMAN_GET_BRANCH_NAME: "ombudsman/getBranchNameByCode/",
  COUNTERFEIT_GET_ALL : "counterfeit",
  COUNTERFEIT_SUBMIT : "counterfeit",
  COUNTERFEIT_EDIT : "counterfeit",
  NCRB_GET : "ncrb"  ,
  NCRB_SUBMIT : "ncrb" ,
  NCRB_EDIT : "ncrb" , 
  FORTNIGHTLY_SUBMIT : "fortnightly",
  GET_FORTNIGHTLY_DATA : "fortnightly",
  UNRECONCILED_SUBMIT : "UnreconciledEntries",
  GET_UNRECONCILED_DATA : "UnreconciledEntries",
  GET_UNRECONCILED_DATA_BY_STATUS : "UnreconciledEntries/byStatus",
  NOSTRO_SUBMIT : "NostroAccounts",
  GET_NOSTRO_DATA : "NostroAccounts",
  GET_NOSTRO_DATA_BY_STATUS : "NostroAccounts/byStatus",
  EQUIFAX_SUBMIT : "equifaxCredit",
  GET_EQUIFAX_DATA : "equifaxCredit",
  EXPOSURE_QCCP_SUBMIT : "ExposureQCCP",
  EXPOSURE_QCCP_GET_RECORDS : "ExposureQCCP",
  TIER1CAPITAL:'ExposureQCCP/tier1Capital',
  OMBUDSMAN_GETBRANCHCODES: "ombudsman/getSerialNumber",
  GET_USER: "userDetails/",
  GET_ALL_USER: "userDetails/allUsers/",
  GET_ALL_SSOUSER: "userDetails/allSSOUsers",
  GET_USER_ROLES: "userDetails/rolesByUsername/",
  AVAILABLE_ROLES: "userDetails/availableRoles/",
  ASSIGNEE_USERS : "userDetails/allSSOUsers",
  COMPLIENCE_USERS : "userDetails/allComplianceUsers",
  USER: "userDetails",
  COMPLIANCE_USERS : "userDetails/allComplianceUsers" , 
  USER_ROLES: "userDetails/rolesByUsername/",
  COMPLIANCE_GET_ALL : "complianceReports",
  COMPLIANCE_GET_SINGLE_RECORD : "complianceReports/getSingleRecord",
  COMPLIANCE_POST_SUBMIT : "complianceReports/",
  COMPLIANCE_SEARCH : "complianceReports/searchByValue",
  DOWNLOAD_EXCEL: "complianceReview/recordsPerCategory/export/excel",
  PATCH_EDIT: "ombudsman/edit",
  INFORMATIONREPORT_SUBMIT:"InformationReport",
  INFORMATIONREPORT_GET:"InformationReport",
  INFORMATIONREPORT_GETBYID:"InformationReport/byId",
  INFORMATIONREPORT_PUT:"InformationReport",
  INFORMATIONREPORT_STATUS:"InformationReport/byStatus",
  OWNERSHIPREPORTS_SUBMIT:"ownershipReports",
  OWNERSHIPREPORTS_STATE:"ownershipReports/state/",
  OWNERSHIPREPORTS_ID:"ownershipReports/ownershipReportId/",
  GET_COUNTRY:"alo/countries",
  ROP_SUBMIT:"rop",
  ROP_GET:"rop",
  CEM_DROPDOWNS:"cem/dropdowns/",
  CEM_SUBMIT:"cem",
  CEM_GET:"cem",
  CEM_DELETE:"cem",
  ALO_SUBMIT:"alo",
  ALO_GET:"alo",
  ANNEXURE_SUBMIT:"alo/annexure-two",
  ANNEXURE_GET:"alo/annexure-two",
  PCI_DROPDOWNS:"pci/dropdowns/",
  PCI_BORROWER_GET:"pci/borrower",
  PCI_BORROWER_SUBMIT:"pci/borrower",
  PCI_BORROWER_DELETE:"pci/borrower",
  PCI_ISSUER_GET:"pci/issuer",
  PCI_ISSUER_SUBMIT:"pci/issuer",
  PCI_ISSUER_DELETE:"pci/issuer",
  GET_KYC_CDD:"kyc-cdd-policies/dropdowns/",
  kYC_CDD_POLICIES_POST:"kyc-cdd-policies",
  kYC_CDD_POLICIES_GET:"kyc-cdd-policies",
  kYC_CDD_POLICIES_PUT:"kyc-cdd-policies",
  LEADS_SRN_DROPDOWN:"leads/srn-dropdown",
  LEADS_INFO:"leads/info",
  GET_LEADS:"leads",
  GET_LEADS_DROPDOWNS:"leads/dropdowns",
  LEADS_SUBMIT:"leads",
  GET_PROFILE_NON_FACE_TO_FACE:"gbmd/nftof-customers-profiles",
  POST_PROFILE_NON_FACE_TO_FACE:"gbmd/nftof-customers-profiles",
  UPDATE_PROFILE_NON_FACE_TO_FACE:"gbmd/nftof-customers-profiles",
  GET_BOJ_RISK_REVIEW_POLICY:"gbmd/boj-risk-review-policy",
  POST_BOJ_RISK_REVIEW_POLICY:"gbmd/boj-risk-review-policy",
  UPDATE_BOJ_RISK_REVIEW_POLICY:"gbmd/boj-risk-review-policy",
  GET_AML_CFT_RMF:"caml/aml-cft-rmf-applications",
  POST_AML_CFT_RMF:"caml/aml-cft-rmf-applications",
  UPDATE_AML_CFT_RMF:"caml/aml-cft-rmf-applications",
  GET_AML_CFT_CRS_MAPPINGS:"caml/aml_cft_crs_cpc_mappings",
  POST_AML_CFT_CRS_MAPPINGS:"caml/aml_cft_crs_cpc_mappings",
  UPDATE_AML_CFT_CRS_MAPPINGS:"caml/aml_cft_crs_cpc_mappings",
  POST_BANK_NEW_PRESENCE:"gbmd/bojny",
  GET_BANK_NEW_PRESENCE:"gbmd/bojny",
  PUT_BANK_NEW_PRESENCE:"gbmd/bojny",
  POST_TRANSACTION_MONITORING:"caml/transaction-monitoring-systems",
  GET_TRANSACTION_MONITORING:"caml/transaction-monitoring-systems",
  PUT_TRANSACTION_MONITORING:"caml/transaction-monitoring-systems",
  GET_NRCB_PROFILE_CONTROLLER:"ibd/new-respondent-correspondent-banks-profiles",
  POST_NRCB_PROFILE_CONTROLLER:"ibd/new-respondent-correspondent-banks-profiles",
  UPDATE_NRCB_PROFILE_CONTROLLER:"ibd/new-respondent-correspondent-banks-profiles",
  GET_RCB_PROFILE_CONTROLLER:"ibd/respondent-correspondent-banks-profiles",
  POST_RCB_PROFILE_CONTROLLER:"ibd/respondent-correspondent-banks-profiles",
  UPDATE_RCB_PROFILE_CONTROLLER:"ibd/respondent-correspondent-banks-profiles",
  POST_RESPONDENT_CORRESPONDENT_BANKS:"ibd/respondent-correspondent-banks-terminated",
  GET_RESPONDENT_CORRESPONDENT_BANKS:"ibd/respondent-correspondent-banks-terminated",
  PUT_RESPONDENT_CORRESPONDENT_BANKS:"ibd/respondent-correspondent-banks-terminated",
  GET_INACTIVE_DORMANT_ACCOUNTS:"caml/inactive-dormant-accounts",
  POST_INACTIVE_DORMANT_ACCOUNTS:"caml/inactive-dormant-accounts",
  UPDATE_INACTIVE_DORMANT_ACCOUNTS:"caml/inactive-dormant-accounts",
  GET_TRANSACTION_Alert:"caml/post-transaction-alerts",
  POST_TRANSACTION_Alert:"caml/post-transaction-alerts",
  UPDATE_TRANSACTION_Alert:"caml/post-transaction-alerts",
  GET_SANCTION_CAUTION_CUSTOMERS: "caml/sanction-caution-customers",
  POST_SANCTION_CAUTION_CUSTOMERS: "caml/sanction-caution-customers",
  UPDATE_SANCTION_CAUTION_CUSTOMERS: "caml/sanction-caution-customers",
  GET_SANCTION_CAUTION_REPORT:"caml/suspicion-reports",
  POST_SANCTION_CAUTION_REPORT:"caml/suspicion-reports",
  UPDATE_SANCTION_CAUTION_REPORT:"caml/suspicion-reports",
  GET_AML_CFT_RELATED_MATTERS:"caml/aml-cft-related-matters",
  POST_AML_CFT_RELATED_MATTERS:"caml/aml-cft-related-matters",
  UPDATE_AML_CFT_RELATED_MATTERS:"caml/aml-cft-related-matters",
  DELETE_AML_CFT_RELATED_MATTERS:"caml/aml-cft-related-matters/",
  GET_OPERATION_CREDIT_REVIEW:"operations-credit-review",
  GET_OPERATION_CREDIT_REVIEW_ACCOUNTS:"operations-credit-review/accounts",
  GET_OPERATION_CREDIT_REVIEW_DETAILS:"operations-credit-review/credit-details",
  POST_OPERATION_CREDIT_REVIEW_DETAILS_UPLOAD:"operations-credit-review/upload",
  POST_OPERATION_CREDIT_REVIEW_DETAILS:"operations-credit-review",
  PUT_OPERATION_CREDIT_REVIEW_DETAILS:"operations-credit-review",
  PUT_OPERATION_CREDIT_REVIEW_STATUS:"operations-credit-review/update-status",
  GET_OPERATION_CREDIT_REVIEW_DROPDOWN:"operations-credit-review/dropdowns",
  GET_CASH_RETENTION_LIMIT:"cash-retention-limit",
  POST_CASH_RETENTION_LIMIT:"cash-retention-limit",
  UPDATE_CASH_RETENTION_LIMIT:"cash-retention-limit",
  BRANCH_NAME_CASH_RETENTION_LIMIT:"cash-retention-limit/branch-name",
  BRANCH_DROPDOWN_CASH_RETENTION_LIMIT:"cash-retention-limit/branch-code-dropdown",
  CURRENCY_NAME_RETENTION_LIMIT:"cash-retention-limit/currency-chest-branch-name",
  CURRENCY_DROPDOWN_RETENTION_LIMIT:"cash-retention-limit/currency-chest-solid-dropdown",
  POST_AML_KYC_COMPLAINTS:"custcare/aml-kyc-complaints",
  UPDATE_AML_KYC_COMPLAINTS:"custcare/aml-kyc-complaints",
  GET_AML_KYC_COMPLAINTS:"custcare/aml-kyc-complaints",
  GET_KYC_AML_DEFICIENCIES:"custcare/kyc-aml-deficiencies",
  POST_KYC_AML_DEFICIENCIES:"custcare/kyc-aml-deficiencies",
  UPDATE_KYC_AML_DEFICIENCIES:"custcare/kyc-aml-deficiencies",
  POST_IT_BASE_TMS_PERFORMANCE:"itd/it-based-tms-performance",
  UPDATE_IT_BASE_TMS_PERFORMANCE:"itd/it-based-tms-performance",
  GET_IT_BASE_TMS_PERFORMANCE:"itd/it-based-tms-performance",
  POST_KYC_AML_DATA:"itd/kyc-aml-data", 
  GET_KYC_AML_DATA:"itd/kyc-aml-data", 
  UPDATE_KYC_AML_DATA:"itd/kyc-aml-data", 
  
  POST_JURISDICTIONS_REVIEW_STATUS:"nil-data/jurisdictions-review-status",
  UPDATE_JURISDICTIONS_REVIEW_STATUS:"nil-data/jurisdictions-review-status",
  GET_JURISDICTIONS_REVIEW_STATUS:"nil-data/jurisdictions-review-status",


  GET_JURISDICTIONS_RISK_PROFILE:"nil-data/jurisdictions-risk-profile",
  POST_JURISDICTIONS_RISK_PROFILE:"nil-data/jurisdictions-risk-profile",
  UPDATE_JURISDICTIONS_RISK_PROFILE:"nil-data/jurisdictions-risk-profile",


  POST_AML_CFT_REVIEW_COMPLIANCE:"iad/aml-cft-auditor-reviews-compliance",
  UPDATE_AML_CFT_REVIEW_COMPLIANCE:"iad/aml-cft-auditor-reviews-compliance",
  GET_AML_CFT_REVIEW_COMPLIANCE:"iad/aml-cft-auditor-reviews-compliance",
  POST_AUDIT:"iad/audit",
  GET_AUDIT:"iad/audit",
  PUT_AUDIT:"iad/audit",
  POST_FACE_TO_FACE_CUSTOMERS:"shares/face-to-face-customers-profile",
  GET_FACE_TO_FACE_CUSTOMERS:"shares/face-to-face-customers-profile",
  PUT_FACE_TO_FACE_CUSTOMERS:"shares/face-to-face-customers-profile",
  POST_AML_CFT_INTERNAL_AUDIT:"iad/aml-cft-internal-audit-reviews",
  GET_AML_CFT_INTERNAL_AUDIT:"iad/aml-cft-internal-audit-reviews",
  PUT_AML_CFT_INTERNAL_AUDIT:"iad/aml-cft-internal-audit-reviews",

};

export const SERVER_PATHS = {

  DEV_HTTP: "http://172.16.15.223:8080/gap-api/api/v1/",
  DEV_HTTPS: "https://172.16.15.223:8443/gap-api/api/v1/",

  PROD_HTTP: "http://ssoedwdcap.edw.obc.co.in:8080/gap-api/api/v1/",
  PROD_HTTPS: "https://ssoedwdcap.edw.obc.co.in:8443/gap-api/api/v1/",

  DEV: "http://172.16.15.223:8080/gap-api/api/v1/",
  LOCAL_HTTP: "http://3.95.36.75:8014/api/v1/",
   
  // LOCAL_HTTP: "http://localhosts:8014/api/v1/",

};
